// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var app, express, platform, port;

  express = require("express");

  platform = require("platform");

  app = express();

  require("dotenv").load();

  app.enable("trust proxy");

  app.get("/", function(req, res) {
    var info, result;
    info = platform.parse(req.headers['user-agent']);
    result = {
      ip: req.ip,
      lang: req.headers["accept-language"].split(",")[0],
      os: info.os.family + " " + info.os.version
    };
    console.log((new Date()) + " : " + result.ip + ", " + result.lang + ", " + result.os);
    return res.send(JSON.stringify(result));
  });

  port = process.env.PORT || 8080;

  app.listen(port, function() {
    return console.log("Server listening on port " + port + "...");
  });

}).call(this);
